### ISSUE TITLE
Sikre input mod injection

### ISSUE THREAD

**Issue by Emilfranord** [ExtraUnity/DDU_database#3]

**Comment by Emilfranord** [comment]
https://medium.com/@mohsinyounas05/different-ways-to-prevent-sql-injection-in-php-cfe03db913bc

https://www.cyber.aau.dk/education/Cybersecurity+Advanced/Cross-site+scripting/

**Comment by LukasMansa** [comment]
(Sign in), (log in) og (add book) er sikret og testet.
Der mangler sikring i søgning af bøger. (Search for book).
